Restrict puppet-lint json gem to older version
The json gem was updated in Oct 2021 to require
a newer version of ruby.
https://rubygems.org/gems/json/versions

This breaks some development environments for running
the linters (puppet-lint) tox target.

Example error message:
  Fetching: json-2.6.1.gem (100%)
  ERROR:  Error installing json:
        json requires Ruby version >= 2.3.

The fix is to clamp the json gem to the previous version.

Story: 2008943
Task: 44060
Signed-off-by: albailey <Al.Bailey@windriver.com>
Change-Id: Ib3e5a59b5d50cceee88abaf22bf15cffbee3c44c